INSERT INTO Users (email,username,private_profile) VALUES ('jpucket','Jeff Puckett',0);
INSERT INTO Users (email,username,private_profile) VALUES ('mengkong','Meng Kong',0);
INSERT INTO Users (email,username,private_profile) VALUES ('vr001','Vignesh Ravichandran',1);
INSERT INTO Users (email,username,private_profile) VALUES ('gw004','Greg Williams',0);
INSERT INTO Users (email,username,private_profile) VALUES ('naliu','Luna',0);
INSERT INTO Users (email,username,private_profile) VALUES ('dbruce','David Bruce',0);
INSERT INTO Users (email,username,private_profile) VALUES ('cam','Chris McCoy',0);
INSERT INTO Users (email,username,private_profile) VALUES ('schabba','Sukhmani Chabba',0);
INSERT INTO Users (email,username,private_profile) VALUES ('dkhan','Danish Khan',0);
INSERT INTO Users (email,username,private_profile) VALUES ('gsphill','Greg Phillips',0);
INSERT INTO Users (email,username,private_profile) VALUES ('gattoun','Gabriel Atoun',0);
