CALL create_content (1,NULL,'Governance','Develop a governance process with ~3 year horizon that is nimble and lightweight to support quick, tactical decisions, but is also inclusive and respectful of campus stakeholders');

CALL create_content (2,NULL,'Strategic Planning','Recommend a strategic planning process with ~3 year horizon that focuses on tactical/operational excellence and identifies immediate strategic moves that are independent of existing constraints');

CALL create_content (3,NULL,'Service Desk','Develop a common service desk model that can be used across the institution to provide 
general walk-in support, telephone support, and field support for office computers, lab computers, major applications, and other services that are typically high volume, fast response services');

CALL create_content (4,NULL,'Desktop Support','Determine whether desktop support is integrated into the service desk or is a separate 
team. Ensure there is a consistent build, deploy, support model for desktop systems that includes the lifecycle (procure, configure, build, load, update, repair, replace');

CALL create_content (2,NULL,'Classroom Technology','Develop a single team that provides broad services across campus to support technologyenabled
classrooms (projectors, media players, Echo360 cameras, cabling/wiring, switching, etc');

CALL create_content (1,NULL,'VDI','Develop a single VDI model that provides services broadly across campus as the designated solution for students, staff and faculty');

CALL create_content (1,NULL,'Software Distro','Develop a single software repository and distribution service that is integrated with existing enterprise to deliver software as licensed to appropriate stakeholders on supported platforms');

CALL create_content (3,NULL,'Software Licensing','Develop a process/procedure for coordinating purchase, distribution and support of software across the institution');

CALL create_content (1, NULL,'Procurement','Define a process/procedure to coordinate technology purchases across campus to improve price points, reduce variety, and coordinate activities to improve support, integration and timing');

CALL create_content (1, NULL,'Labs','Define a standard for general-purpose, student computer laboratories that provides common services at a high level across the campus');

CALL create_content (1,NULL,'Printing','Define a single, widely-adopted managed print solution that includes print quotas, printer device support and shared usage');

CALL create_content (3,NULL,'Telephony','Enterprise Technologies');
CALL create_content (1,NULL,'ERP','Enterprise Technologies',);
CALL create_content (1,NULL,'Email/Collaboration Suite','Enterprise Technologies',);
CALL create_content (1,NULL,'Network','Enterprise Technologies',);
CALL create_content (2,NULL,'Active Directory','Enterprise Technologies',);
CALL create_content (1,NULL,'SharePoint','Enterprise Technologies',);
CALL create_content (1,NULL,'Web Service','Enterprise Technologies',);
CALL create_content (4,NULL,'Enterprise Architecture','Infrastructure');
CALL create_content (1,NULL,'Project Management','Infrastructure');
CALL create_content (1,NULL,'Data Center','Infrastructure');
CALL create_content (1,NULL,'High Performance Computing','Infrastructure');
CALL create_content (1,NULL,'Identity and Access Management (IAM)','Security');
CALL create_content (2,NULL,'Security Incident and Event Monitoring (SIEM)','Security');
CALL create_content (1,NULL,'Network Security Architecture','Security');